version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      PGDATA: /data/postgres

    ports:
      - "5433:5432"
    volumes:
      - ./database/postgres:/data/postgres
    networks:
      - mynetwork

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DOCKER_PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DOCKER_PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "5050:80"
    volumes:
      - ./database/pgadmin:/root/.pgadmin
    networks:
      - mynetwork

  fastapi:
    build: src/.
    restart: on-failure
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./src/app/:/src/app/
    networks:
      - mynetwork
    depends_on:
      - postgres

  test_postgres:
    container_name: test_postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "test_postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/test_postgres

    ports:
      - "5434:5432"
    volumes:
      - ./database/test_postgres:/data/test_postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
